apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-app
  template:
    metadata:
      labels:
        app: social-app
    spec:
      containers:
      - name: social-app
        image: social:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: social-app-config
        ports:
        - containerPort: 8080
