on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up and Deploy
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        $env:KUBECONFIG = "kubeconfig.yaml"
        kubectl version --client
        kubectl config get-contexts
        kubectl config use-context docker-desktop
        kubectl apply -f ./k8s/
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}