on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Set Git Debug Environment Variable
      run: |
        echo "GIT_TEST_DEBUG_UNSAFE_DIRECTORIES=true" >> $GITHUB_ENV
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Configure Git
      run: |
        git config --global --add safe.directory D:/actions-runner/_work/social-test/social-test

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build app image
      run: |
        docker build -t atasik/social:latest .
        docker push atasik/social:latest
    
    - name: Deploy
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        $env:KUBECONFIG = "kubeconfig.yaml"
        kubectl version --client
        kubectl config get-contexts 
        kubectl config use-context docker-desktop
        kubectl apply -f ./k8s/
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      
